### ISSUE TITLE
[EDIT] Audio waveforms are very small unless tracks are made large

### ISSUE THREAD

**Issue by wezm** [olive-editor/olive#2014]
**Commit Hash** 402c4e16

**Platform** Linux (Arch)

**Summary**

Editing based on audio tracks is difficult at the default track size. Making the tracks quite a bit larger with Ctrl-+ helps but then you often can't see several tracks at once and need to scroll the tracks up and down.

**Additional Information / Output**

Just for additional context I am using Olive fullscreen on a 24" 4K display running at 2x (so 1920x1080 points) to give some idea of the screen real estate I'm working with.

Additionally here is [some commentary from Marta Gvozdinskaya](https://discord.com/channels/549629829730009089/550238656468746261/1007897075956072508) on Discord describing the same issue:

> I've finished the first project in Olive 0.2 :) It's a low effort but I've noticed a few things.
Firstly, I still think that waveform is too small within a track. This is normal-ish youtube loudness and voice only, had to really enlarge the tracks to cut it comfortably:

![waveform0 2](https://user-images.githubusercontent.com/21787/185288951-90f79a3d-da8b-4b90-a8a6-4f4a2655b47a.png)

> For comparison, in Olive 0.1 the padding on the top and the bottom of the track was smaller, there I can easily cut silences close to the voice without enlarging the tracks:

![waveform0 1](https://user-images.githubusercontent.com/21787/185288963-e414ac25-73b0-462c-b322-763c47e3c8f3.png)

**Comment by itsmattkc** [comment]
The waveforms are not "very small", they're objectively correct. You can see if the audio is amplified beyond peaking that there is actually no padding whatsoever apart from the clip title: 
![image](https://user-images.githubusercontent.com/34096995/185421728-de51f981-2457-441d-aeb4-34eff3a5997d.png)

The being said I recognize that the clip title is thus wasted space and, while I initially thought that was a neater way to layout the clips, it seems other editors do utilize that space, so I've done that, which should resolve this issue.

**Comment by wezm** [comment]
Thanks Matt. Still getting the hang of editing videos and it's likely that my microphone needs a boost in post so that probably exacerbated the effect. Using the space in the clip title seems like a good improvement nonetheless.
