### ISSUE TITLE
Export Failed - Failed to send frame to encoder (-542398533)

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#227]
System: Wacom Cintiq Companion 2, Windows 10 - 64bit
Processor: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz 

For some reason, I can't export a film due to this error after the export process stops at 2%:

`Export failed - failed to send frame to encoder (-542398533)`

At first this was because I was trying out an imported footage that is HEVC(x265) encoded and that it could be having trouble reading frames from the video file, but when I was trying out a quicktime MOV file, it still had the same error.

Figure I let you know about this bug.

(Quick Edit: I changed the libx264 H.264/AVC/MPEG-4 AVC/MPEG-4 Part 10 codec to another codec and the percentage went higher than 2%, maybe a codec exporting problem?)

**Comment by itsmattkc** [comment]
There was a bug that produced this error that was fixed, but the build on the website hasn't been updated for it yet. If you'd like, try this newer compile (just replace the .exe file) and see if that solves the issue.
[olive-editor.zip](https://github.com/olive-editor/olive/files/2719898/olive-editor.zip)

**Comment by Corruptinator** [comment]
Ok, thanks. I'll check it out.

**Comment by Corruptinator** [comment]
Error is gone but now the exported video is a little bugged out. I opened up VLC to see how the picture looks but all I get is a completely black screen, and the audio plays out a sample of the track every 1 second, but goes silent afterwards. However, when I open up Windows Media Player, the audio plays fine but the video goes completely glitched out everywhere to the point its completely unwatchable.

**Comment by itsmattkc** [comment]
What were your export settings? I assume it plays correctly in the timeline?

**Comment by Corruptinator** [comment]
I'm going to test another footage and see if its still showing the same glitch.

**Comment by Corruptinator** [comment]
![image](https://user-images.githubusercontent.com/5027750/50580733-43689c80-0e07-11e9-8a3e-c163308c549d.png)

**Comment by Corruptinator** [comment]
I'm going to test another footage to export, I think it may possibly be a framerate issue.

**Comment by itsmattkc** [comment]
Oh that's interesting, so the issue only occurs when exporting MKV? It's true that I haven't tested exporting much outside of MP4/H.264. Yes, feel free to submit any issues you find.

**Comment by Corruptinator** [comment]
Thanks.
