### ISSUE TITLE
Pressing another mouse button while dragging a LabelSlider "kills" the cursor

### ISSUE THREAD

**Issue by manokara** [olive-editor/olive#449]
Tested with 101ad79.

I noticed this because my mouse's right button is quite sensitive, and I accidentally pressed it. It also happens with the middle button. The cursor is entirely gone, but only inside Olive - it shows fine in other applications. Dragging the label again and releasing it doesn't restore the cursor.

**Comment by manokara** [comment]
This still happens when right-clicking, probably because of the popup menu. A workaround could be something like this:

```
} else if (ev->button() == Qt::RightButton && drag_start) {
    drag_start = false;
    qApp->restoreOverrideCursor();
}
```

And while it works, if I do it too fast the cursor is not restored - I suspect the event fires so fast it gets to `drag_start = false` and skips `qApp->restoreOverrideCursor()`. Well, it's not something super serious, but new users that may stumble upon this could get confused.

**Comment by itsmattkc** [comment]
Strange, this fixed it on my end. Perhaps one of those weird UI inconsistencies between platforms.

I've implemented a solution similar to yours in 0ad58a6930ee859a1459c66f49b7dddc6a1c1fcb, let me know if that fixes this properly.

**Comment by manokara** [comment]
It does, sort of. I notice that what actually happens is that `Qt::BlankCursor` may get pushed more than one time to the cursor override stack. I tweaked my original solution to be this:

```
inline void restoreCursor() {
    while (qApp->overrideCursor())
        qApp->restoreOverrideCursor();
}

void LabelSlider::mouseReleaseEvent(QMouseEvent *ev) {
    if (drag_start) {
        // unhide cursor
        restoreCursor();
        // ...
    }
    
    restoreCursor();
}
```

Putting `restoreCursor()` in and out of the if block just in case. And it fixes it for the most part, but still doesn't work when I move it too fast. I'm not even sure if it's moving too fast, maybe it's pressing many buttons at the same time (while also moving fast). But then that's just me QA'ing too much, normally a user shouldn't experience that corner case.

I'd assume it has to do with the event context being switched to the popup menu. Using the while loop approach helps to bring the cursor back by just dragging it again.

*offtopic: that commit seems to have borked loading a project from the command line. There's a mutex error, the loading dialog is frozen and clicking Cancel segfaults.*

**Comment by itsmattkc** [comment]
With further testing, it does seem the menu may be triggering/preventing the mouse press/release events from firing. I still wasn't able to recreate this issue exactly so I've tried a more "catch-all" solution in that I set the widget's cursor specifically rather than overriding the whole app's cursor in a9897f1b1020a397068eb3ac86a0fbfc96e37889.

Sometimes the user can break this and drag the LabelSlider with the cursor visible, but I think that's preferable to the cursor disappearing from Olive permanently and forcing the user to restart.
